use rocket_sync_db_pools::rusqlite::Connection;

#[allow(unused_assignments)]
pub fn init_database(conn: &Connection) {
    fn upgrade_message(version: usize) {
        println!("Upgrading DB version {}, stand by...", version);
    }

    let mut db_version: i64 = conn
        .query_row("PRAGMA user_version", [], |row| row.get(0))
        .expect("lookup db table version");

    if db_version == 0 {
        upgrade_message(0);

        conn.execute(
            "CREATE TABLE users (
                id              INTEGER PRIMARY KEY,
                name            TEXT NOT NULL,
                NBR             REAL NOT NULL,
                password        TEXT,
                time_created    TEXT NOT NULL
            )",
            [],
        )
        .expect("create users table");

        conn.execute(
            "CREATE TABLE products (
                id          INTEGER PRIMARY KEY,
                name        TEXT NOT NULL,
                gateway     REAL NOT NULL,
                benefit     REAL NOT NULL,
                time_created    TEXT NOT NULL,
                resabundance    REAL,
                beneficiaries   REAL,
                producers       REAL,
                ccs             REAL,
                conssubben      REAL,
                cco             REAL,
                consobjben      REAL,
                ceb             REAL,
                envben          REAL,
                chb             REAL,
                humanben        REAL
            )",
            [],
        )
        .expect("create products table");

        conn.execute(
            "CREATE TABLE transfers (
                id          INTEGER PRIMARY KEY,
                ConsumerID     INTEGER NOT NULL,
                ProducerID     INTEGER NOT NULL,
                ProductID      INTEGER NOT NULL,
                amount         REAL NOT NULL,
                NBR            REAL NOT NULL,
                GNBR           REAL NOT NULL,
                time_created   TEXT NOT NULL,
                comment        TEXT
            )",
            [],
        )
        .expect("create transfers table");
        conn.execute("INSERT OR IGNORE INTO users (id, name, NBR, password, time_created)
        VALUES (0, '-', 0, 0, datetime('now','localtime'))", [])
            .expect("insert single entry into table");

        conn.execute(
            "CREATE TABLE user_products (
                ProductID      INTEGER,
                UserID         INTEGER,
                gateway        REAL NOT NULL,
                benefit        REAL NOT NULL,
                time_created   TEXT NOT NULL,
                resabundance   REAL,
                beneficiaries  REAL,
                producers      REAL,
                ccs            REAL,
                conssubben     REAL,
                cco            REAL,
                consobjben     REAL,
                ceb            REAL,
                envben         REAL,
                chb            REAL,
                humanben       REAL,
                PRIMARY KEY (ProductID, UserID)
            )",
            [],
        )
        .expect("create user_products table");

        db_version = 4;
    }

    // Insert blood types only if the `users` table is empty
    let user_count: i64 = conn.query_row("SELECT COUNT(*) FROM users", [], |row| row.get(0))
        .expect("check users table count");

    // List of blood types to add to the users table
    if user_count == 1 {
        let blood_types = vec![
            "Blood Type A Secretor",
            "Blood Type A Non-Secretor",
            "Blood Type AB Secretor",
            "Blood Type AB Non-Secretor",
            "Blood Type B Secretor",
            "Blood Type B Non-Secretor",
            "Blood Type O Secretor",
            "Blood Type O Non-Secretor",
        ];

        for blood_type in blood_types {
            conn.execute(
                "INSERT INTO users (
                    name, NBR, password, time_created
                ) VALUES (?1, 0.0, 0.0, datetime('now', 'localtime'))",
                &[&blood_type],
            )
            .expect("insert blood type into users table");
        }

        // List of food names to add to the products table
        let food_names = vec![
            "Abalone, Sea-Ears, Muttonshells",
            "Acacia (Arabic Gum)",
            "Acai Berries",
            "Adzuki Beans",
            "Agar",
            "Agave Syrup",
            "Alfalfa Sprouts",
            "Alfalfa Tea",
            "Allspice",
            "Almond Butter",
            "Almond Cheese",
            "Almond Extract",
            "Almond Oil",
            "Almonds",
            "Aloe Juice",
            "Aloe Tea",
            "Aloe Vera",
            "Amaranth",
            "American Cheese",
            "Anchovy",
            "Anise",
            "Apple",
            "Apple Butter",
            "Apple Juice",
            "Apple cider",
            "Apricot Juice",
            "Apricot Kernel Oil",
            "Apricots",
            "Arrowroot",
            "Artichoke",
            "Artichoke Flour, Pasta",
            "Arugula",
            "Asian Pear",
            "Asparagus",
            "Asparagus Peas",
            "Aspartame",
            "Avocado",
            "Avocado Oil",
            "Babassu Oil",
            "Baking Soda",
            "Balsam Pear, Bitter Gourd",
            "Bamboo Shoot",
            "Banana",
            "Barley",
            "Barley Flour",
            "Barley Malt",
            "Barracuda",
            "Basil",
            "Bass, Sea, Lake",
            "Bass, Striped",
            "Bay Leaf",
            "Beans, String, Green, Snap",
            "Bear",
            "Beechnuts",
            "Beef",
            "Beer",
            "Beet Greens",
            "Beet Juice",
            "Beets",
            "Bergamot",
            "Bison, Buffalo",
            "Bitter Melon",
            "Black Bean Flour",
            "Black Beans",
            "Black Cherry Juice",
            "Black Currant Seed Oil",
            "Black Eyed Peas",
            "Black Tea, all forms",
            "Blackberries",
            "Blackberry Juice",
            "Blue Cheese",
            "Blueberries",
            "Blueberry Juice",
            "Bluefish",
            "Bok Choy, Pak Choi",
            "Bone Soup (allowable meats)",
            "Borage",
            "Borage Seed Oil",
            "Boysenberries",
            "Brazil Nuts",
            "Breadfruit",
            "Brie Cheese",
            "Broad Beans, Fava",
            "Broccoflower",
            "Broccoli",
            "Broccoli Leaves",
            "Broccoli Rabe, Rapini",
            "Broccoli, Chinese",
            "Brown Rice Syrup",
            "Brussels Sprout",
            "Buckwheat, Kasha, Soba",
            "Bulgur Wheat Flour",
            "Bullhead",
            "Burdock Tea",
            "Butter",
            "Butter Beans",
            "Butterfish",
            "Butternuts",
            "Cabbage",
            "Cabbage Juice",
            "Camelina Oil",
            "Camembert Cheese",
            "Canang Melon, Cantaloupe",
            "Canistel",
            "Cannellini Beans",
            "Canola Oil",
            "Cantaloupe Melon",
            "Caper",
            "Caraway",
            "Cardamom",
            "Caribou",
            "Carissa, Natal Plum",
            "Carob",
            "Carp",
            "Carp Roe",
            "Carrageenan",
            "Carrageenan/ Irish moss",
            "Carrot Juice",
            "Carrots",
            "Casaba Melon",
            "Casein",
            "Cashew Butter",
            "Cashews",
            "Cassava",
            "Catfish",
            "Catnip Tea",
            "Cauliflower",
            "Caviar",
            "Cayenne Tea",
            "Celeriac",
            "Celery",
            "Celery Juice",
            "Celery Seed",
            "Celtuce",
            "Chamomile Tea",
            "Chayote, Pipinella, Vegetable Pear",
            "Cheddar Cheese",
            "Cheese, Goat",
            "Cherimoya",
            "Cherries",
            "Cherry Juice",
            "Chervil",
            "Cheshire Cheese",
            "Chestnuts, Chinese",
            "Chestnuts, European",
            "Chia Seed Oil",
            "Chia Seeds, Pinole",
            "Chicken",
            "Chickweed Tea",
            "Chicory",
            "Chicory Root",
            "Chili Powder",
            "Chinese Kale, Kai-lan",
            "Chives",
            "Chocolate",
            "Christmas Melon",
            "Chub",
            "Cilantro",
            "Cinnamon",
            "Clam",
            "Cloudberries",
            "Clove",
            "Club Soda",
            "Coconut Meat",
            "Coconut Milk",
            "Coconut Oil",
            "Coconut Water",
            "Cod",
            "Cod Liver Oil",
            "Coffee",
            "Colby Cheese",
            "Collard Greens",
            "Coltsfoot Tea",
            "Conch",
            "Copper Beans",
            "Coriander",
            "Corn",
            "Corn Oil",
            "Corn Silk Tea",
            "Corn Syrup",
            "Corn, Grits",
            "Corn, Popcorn",
            "Cornflakes",
            "Cornish Hen",
            "Cornmeal, Hominy, Polenta",
            "Cornstarch",
            "Cottage Cheese",
            "Cottonseed Oil",
            "Crab",
            "Cranberries",
            "Cranberry Juice",
            "Crayfish",
            "Cream Cheese",
            "Cream of Rice",
            "Cream of Tartar",
            "Cream of Wheat",
            "Crenshaw Melon",
            "Croaker",
            "Cucumber",
            "Cucumber Juice",
            "Cumin",
            "Currants",
            "Curry",
            "Cusk",
            "Daikon Radish",
            "Dandelion Greens",
            "Dandelion Tea",
            "Dates",
            "Dewberries",
            "Dextrose",
            "Dill",
            "Dong Quai Tea",
            "Drum",
            "Duck",
            "Duck, Liver",
            "Dulse",
            "Durian",
            "Echinacea Tea",
            "Edam Cheese",
            "Eel",
            "Egg White, Chicken",
            "Egg White, Duck",
            "Egg Whole, Chicken",
            "Egg Whole, Duck",
            "Egg Yolk, Chicken",
            "Eggplant",
            "Elder Tea",
            "Elderberries",
            "Elderberry Juice",
            "Emmenthal, Swiss Cheese",
            "Emu",
            "Endive",
            "Epazote",
            "Escarole",
            "Essene, Manna Bread",
            "Evening Primrose Oil",
            "Familia",
            "Farina",
            "Farmer Cheese",
            "Farro",
            "Feijoa",
            "Fennel",
            "Fennel (spice)",
            "Fenugreek",
            "Fenugreek Tea",
            "Feta Cheese",
            "Fiddlehead Fern",
            "Figs",
            "Filberts, Hazelnuts",
            "Flax Seed, Linseed Oil",
            "Flax Seeds",
            "Flaxseed Bread (containing allowable grains)",
            "Flounder",
            "Fonio",
            "Frog",
            "Fructose",
            "Fruit Pectin",
            "Garbanzo Beans, Chickpeas",
            "Garbanzo bean flour",
            "Garlic",
            "Gelatin, Plain",
            "Gentian Tea",
            "Ghee, Clarified Butter",
            "Ginger",
            "Ginger Root Tea",
            "Ginseng Tea",
            "Gluten Flour",
            "Goat",
            "Goji Berry juice",
            "Goji, Wolfberry",
            "Goldenseal Tea",
            "Goose",
            "Goose Egg",
            "Gooseberry",
            "Gorgonzola Cheese",
            "Gouda Cheese",
            "Graham Flour",
            "Grape Juice",
            "Grape Leaves",
            "Grape Nuts",
            "Grape Seed Oil",
            "Grapefruit",
            "Grapefruit Juice",
            "Grapes",
            "Gray Sole",
            "Great Northern Beans",
            "Green Bean",
            "Green Tea, Kukicha, Bancha",
            "Groundcherries, Cape Gooseberry, Poha",
            "Grouper",
            "Grouse",
            "Gruyere Cheese",
            "Guar Gum",
            "Guarana",
            "Guava",
            "Guava Juice",
            "Guinea Hen",
            "Haddock",
            "Hake",
            "Half & Half",
            "Halfmoon Fish",
            "Halibut",
            "Ham",
            "Haricot Beans",
            "Harvest Fish",
            "Havarti Cheese",
            "Hawthorn Tea",
            "Hazelnut Nut Oil",
            "Heart, Beef",
            "Hearts of Palm",
            "Hemp Seed Oil",
            "Hemp Seeds",
            "Herring",
            "Herring Oil",
            "Herring Roe",
            "Hickory Nuts",
            "High Fructose Corn Syrup",
            "High Maltose Corn Syrup, Maltodextrin",
            "Honey",
            "Honeydew Melon",
            "Hops Tea",
            "Horehound Tea",
            "Horse",
            "Horseradish",
            "Huckleberries",
            "Ice Cream",
            "Invert Sugar",
            "Jack Fruit",
            "Jam, Jelly (acceptable fruit)",
            "Jarlsberg Cheese",
            "Java-plum, Jambolan",
            "Jellyfish, dried, salted",
            "Jerusalem Artichoke",
            "Jew's Ear, Pepeao",
            "Jicama",
            "Job's Tears, Coix spp.",
            "Jujube",
            "Junniper",
            "Jute, Potherb",
            "Kale",
            "Kangaroo",
            "Kanpyo, Dried Gourd Strips",
            "Kefalotyri Cheese",
            "Kefir",
            "Ketchup",
            "Kidney Beans",
            "Kiwi",
            "Kohlrabi",
            "Kombucha Tea",
            "Kudzu",
            "Kumquat",
            "Lamb",
            "Larch Fiber",
            "Lard",
            "Lecithin",
            "Leeks",
            "Lemon",
            "Lemon Balm Tea",
            "Lemon Grass, Citronella",
            "Lemon and Water",
            "Lentil Flour, Dahl",
            "Lentils, Sprouted",
            "Lentils, all types",
            "Lettuce, Green Leaf, Iceberg",
            "Lettuce, Romaine",
            "Licorice Root",
            "Licorice Root Tea",
            "Lima Bean Flour",
            "Lima Beans",
            "Limburger Cheese",
            "Lime",
            "Lime Juice",
            "Linden Tea",
            "Lingonberries",
            "Liquor, Distilled",
            "Litchi Nuts",
            "Liver, Beef",
            "Liver, Calf",
            "Liver, Chicken",
            "Liver, Goose",
            "Lobster",
            "Loganberries",
            "Loquat",
            "Lotus Seeds",
            "Lotus root",
            "Lupin Seeds",
            "MSG",
            "Macadamia Nuts",
            "Macadamia Oil",
            "Mace",
            "Mackerel, Atlantic",
            "Mackerel, Spanish",
            "Mahi-mahi",
            "Malanga, Tannier, Xanthosoma",
            "Mamey Sapote, Mammy Apple",
            "Manchego Cheese",
            "Mango",
            "Mango Juice",
            "Mangosteen",
            "Maple Syrup",
            "Margarine",
            "Marjoram",
            "Marrow Soup",
            "Mastic Gum",
            "Mayonnaise",
            "Mayonnaise, Tofu, Soy",
            "Methyl Cellulose",
            "Milk Thistle Tea",
            "Milk, Almond",
            "Milk, Buttermilk",
            "Milk, Cow-Skim or 2%",
            "Milk, Cow-Whole",
            "Milk, Goat",
            "Milk, Indian buffalo",
            "Milk, Rice",
            "Milk, Soy",
            "Millet",
            "Molasses",
            "Molasses, Blackstrap",
            "Monkfish",
            "Monterey Jack Cheese",
            "Moose",
            "Mothbeans",
            "Mountain Yam",
            "Mozzarella Cheese, all types",
            "Muenster Cheese",
            "Mulberries",
            "Mulberry Tea",
            "Mullein Tea",
            "Mullet",
            "Mung Beans, Sprouts",
            "Mushroom, Abalone (Tree)",
            "Mushroom, Black Trumpet",
            "Mushroom, Brown, Crimini",
            "Mushroom, Enoki",
            "Mushroom, Maitake",
            "Mushroom, Oyster",
            "Mushroom, Portobella",
            "Mushroom, Shiitake",
            "Mushroom, Straw",
            "Mushroom, White, Silver Dollar",
            "Musk Melon",
            "Muskellunge",
            "Mussels",
            "Mustard Greens",
            "Mustard, Dry",
            "Mustard, Wheat-free, Vinegar-free",
            "Mustard, with Vinegar and Wheat",
            "Mutton",
            "Natto",
            "Navy Beans",
            "Nectarine",
            "Nectarine Juice",
            "Neufchatel Cheese",
            "Noni",
            "Noni Juice",
            "Nutmeg",
            "Oat Bran",
            "Oat Oil",
            "Oatmeal, Oat Flour, Oats",
            "Ocean Pout",
            "Octopus",
            "Okra",
            "Olive Oil",
            "Olives, Black",
            "Olives, Green",
            "Onion, all types",
            "Opaleye Fish",
            "Opossum",
            "Orange",
            "Orange Juice",
            "Orange Roughy",
            "Oregano",
            "Ostrich",
            "Oyster",
            "Oyster Plant, Salsify",
            "Palm Oil",
            "Paneer Cheese",
            "Papadam",
            "Papaya",
            "Papaya Juice",
            "Paprika",
            "Parmesan Cheese",
            "Parrotfish",
            "Parsley",
            "Parsley tea",
            "Parsnips",
            "Partridge",
            "Passion Fruit",
            "Paw Paw",
            "Peach",
            "Peanut Butter",
            "Peanut Flour",
            "Peanut Oil",
            "Peanuts",
            "Pear",
            "Pear Juice",
            "Peas",
            "Pecan Butter",
            "Pecans",
            "Pecorino Cheese",
            "Pectin, Apple",
            "Pepper, Black",
            "Pepper, Cayenne",
            "Peppermint",
            "Peppermint Tea",
            "Peppers, Bell",
            "Peppers, Chili, Jalapeno",
            "Perch",
            "Perch, Ocean",
            "Perilla Seed Oil",
            "Persian Melon",
            "Persimmon",
            "Pheasant",
            "Pickerel, Walleye",
            "Pickle Relish",
            "Pickle, Brine",
            "Pickle, Vinegar",
            "Pike",
            "Pilchards",
            "Pimento",
            "Pine Nuts, Pignola",
            "Pineapple",
            "Pineapple Juice",
            "Pinto Beans",
            "Pinto Beans, Sprouted",
            "Pistachio Nuts",
            "Plantain",
            "Plums",
            "Pollock, Atlantic",
            "Polysorbate 80",
            "Pomegranate",
            "Pomegranate Juice",
            "Pompano",
            "Poppy Seeds",
            "Porgy",
            "Pork, Bacon",
            "Port de Salut Cheese",
            "Potato, White with Skin",
            "Prickly Pear",
            "Provolone Cheese",
            "Prune Juice",
            "Prunes",
            "Pummelo",
            "Pummelo Juice",
            "Pumpkin",
            "Pumpkin Flowers",
            "Pumpkin Seed Oil",
            "Pumpkin Seeds",
            "Purslane",
            "Quail",
            "Quail Egg",
            "Quark Cheese",
            "Quince",
            "Quinoa",
            "Quinoa Oil",
            "Quorn",
            "Rabbit",
            "Radicchio",
            "Radish Sprouts",
            "Radishes",
            "Raisins",
            "Raspberries",
            "Raspberry Leaf Tea",
            "Red Clover Tea",
            "Red Snapper",
            "Rhubarb",
            "Rhubarb Tea",
            "Rice Bran",
            "Rice Bran Oil",
            "Rice Flour, Brown",
            "Rice Flour, White",
            "Rice Syrup",
            "Rice, Basmati",
            "Rice, Brown",
            "Rice, Puffed or Rice Cakes",
            "Rice, White",
            "Rice, Wild",
            "Ricotta Cheese",
            "Romanian Urda",
            "Romano Cheese",
            "Rooibos Tea",
            "Roquefort Cheese",
            "Rosefish",
            "Rosehip Tea",
            "Roselle",
            "Rosemary",
            "Rowal",
            "Rowanberries",
            "Rutabaga",
            "Rye",
            "Rye Berry",
            "Rye Flour",
            "Safflower Oil",
            "Safflower Seeds",
            "Saffron",
            "Sage",
            "Sage Tea",
            "Sago Palm",
            "Sailfish",
            "Sailfish Roe",
            "Saint John's Wort Tea",
            "Salad Dressing (acceptable ingredients)",
            "Salmon Oil",
            "Salmon Roe",
            "Salmon, Atlantic, wild",
            "Salmon, Chinook",
            "Salmon, Smoked, Lox",
            "Salmon, Sockeye",
            "Sapodilla",
            "Sapotes, Marmalade Plum",
            "Sardine",
            "Sarsaparilla Tea",
            "Sauerkraut",
            "Savory",
            "Scallion",
            "Scallops",
            "Scrod",
            "Scup",
            "Sea Bream",
            "Sea Cucumber",
            "Sea Salt",
            "Sea Vegetables, Irish Moss",
            "Sea Vegetables, Kelp, Kombu, Nori, Bladderwrack",
            "Sea Vegetables, Wakame",
            "Seltzer Water",
            "Senna",
            "Senna Tea",
            "Sesame Butter, Tahini",
            "Sesame Flour",
            "Sesame Oil",
            "Sesame Seed",
            "Seven Grain (non-sprouted)",
            "Shad",
            "Shallots",
            "Shark",
            "Shea Nut Oil",
            "Sheepshead fish",
            "Shepherd's Purse Tea",
            "Shredded Wheat",
            "Shrimp",
            "Skate",
            "Skullcap Tea",
            "Slippery Elm Tea",
            "Smelt",
            "Snail, Escargot",
            "Soda (commercial, diet)",
            "Sodium Carboxymethyl Cellulose",
            "Sole",
            "Sorghum",
            "Sour Cream",
            "Soy Flakes",
            "Soy, Miso",
            "Soybean Beans",
            "Soybean Flour",
            "Soybean Granules, Lecithin",
            "Soybean Meal",
            "Soybean Oil",
            "Soybean Pasta",
            "Soybean Sauce, Tamari, Wheat-free",
            "Soybean, 'Cheese'",
            "Soybean, Sprouted",
            "Soybean, Tempeh",
            "Soybean, Tofu",
            "Spanish Melon",
            "Spearmint",
            "Spearmint Tea",
            "Spelt Flour, Noodles",
            "Spinach",
            "Spirulina",
            "Squab",
            "Squash",
            "Squid, Calamari",
            "Squirrel",
            "Starfruit, Carambola",
            "Stevia",
            "Stilton Cheese",
            "Strawberries",
            "Strawberry Leaf Tea",
            "String Cheese",
            "Sturgeon",
            "Sucanat",
            "Sucker",
            "Sugar, Brown, White",
            "Sunfish, Pumpkinseed",
            "Sunfish, bluegill",
            "Sunflower Butter",
            "Sunflower Oil",
            "Sunflower Seeds",
            "Swamp Cabbage, Skunk Cabbage",
            "Sweet Potato",
            "Sweet Potato Leaves",
            "Sweetbreads",
            "Swiss Chard",
            "Swordfish",
            "Tamarillos",
            "Tamarind Bean",
            "Tangerine",
            "Tangerine Juice",
            "Tapioca, Manioc, Cassava, Yuca",
            "Taro Leaves, Shoots",
            "Taro, Tahitian, Poi, Dansheen",
            "Tarragon",
            "Tea Seed Oil",
            "Teff",
            "Thyme",
            "Thyme Tea",
            "Tilapia",
            "Tilefish",
            "Tomatillo",
            "Tomato",
            "Tomato Juice",
            "Tongue, Beef",
            "Tragacanth Gum",
            "Trout, Rainbow, Wild",
            "Trout, Sea",
            "Trout, Steelhead, Wild",
            "Tuna, Bluefin",
            "Tuna, Skipjack",
            "Tuna, Yellowfin",
            "Turbot, European",
            "Turkey",
            "Turmeric",
            "Turnip Greens",
            "Turnips",
            "Turtle",
            "Umeboshi Plum, Vinegar",
            "Valerian Tea",
            "Vanilla",
            "Veal",
            "Vegetable Glycerine",
            "Vegetable Juices (from acceptable vegetables)",
            "Vegetable Juices (from beneficial vegetables)",
            "Venison",
            "Vervain Tea",
            "Vinegar, apple cider",
            "Vinegar, except apple cider",
            "Walnut Oil",
            "Walnut, English",
            "Walnuts",
            "Water Chestnut, Matai",
            "Watercress",
            "Watermelon",
            "Watermelon Juice",
            "Watermelon Seeds",
            "Wax Gourd (Chinese Preserving Melon)",
            "Weakfish",
            "Wheat Germ Oil",
            "Wheat, Bran, Germ",
            "Wheat, Bulgur",
            "Wheat, Durum, Semolina, Couscous",
            "Wheat, Puffed",
            "Wheat, Sprouted",
            "Wheat, Whole Grain Emmer",
            "Wheat, Whole Grain Flour, White Flour",
            "Wheat, Whole Grain Kamut",
            "Wheat, Whole Grain Spelt",
            "Whey Protein Powder",
            "White Beans",
            "White Birch Tea",
            "White Oak Bark Tea",
            "Whitefish",
            "Whiting",
            "Wine, Red",
            "Wine, White",
            "Winged Beans",
            "Wintergreen",
            "Wolfish, Atlantic",
            "Worcestershire Sauce",
            "Yam",
            "Yardlong Beans",
            "Yarrow Tea",
            "Yeast Extract Spread, Marmite",
            "Yeast, Bakers",
            "Yeast, Brewers",
            "Yeast, Nutritional",
            "Yellow Dock Tea",
            "Yellowfish",
            "Yellowtail",
            "Yerba Mate Tea",
            "Yogurt",
            "Youngberries",
            "Zucchini"			
        ];

        // Insert each food name into the products table with default values
        for food_name in food_names {
            conn.execute(
                "INSERT INTO products (
                    name, gateway, benefit, time_created, resabundance, beneficiaries,
                    producers, ccs, conssubben, cco, consobjben, ceb, envben, chb, humanben
                ) VALUES (?1, 0.0, 0.0, datetime('now', 'localtime'), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)",
                &[&food_name],
            )
            .expect("insert food into products table");
        }
    }

    if db_version < 4 {
        panic!("DB upgrade not implemented!");
    }
    
    if db_version == 4 {
        upgrade_message(4);
        conn.execute(
            "ALTER TABLE users ADD COLUMN fame REAL NOT NULL DEFAULT 0",
            [],
        )
        .expect("alter db add column");
        conn.execute("UPDATE users SET fame = NBR", [])
            .expect("update users fame");
        conn.execute("PRAGMA user_version = 5", [])
            .expect("alter db version");
        db_version = 5;
    }
}
